/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ContactsOutlined: typeof import('@ant-design/icons-vue')['ContactsOutlined']
    EmailOutlined: typeof import('@ant-design/icons-vue')['EmailOutlined']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    LockOutlined: typeof import('@ant-design/icons-vue')['LockOutlined']
    MailOutlined: typeof import('@ant-design/icons-vue')['MailOutlined']
    PhoneOutlined: typeof import('@ant-design/icons-vue')['PhoneOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
  }
}
