module.exports = {
  env: {
    browser: true,
    es2021: true,
    node: true,
  },
  extends: ["common", "plugin:react/recommended", "plugin:react/jsx-runtime", "prettier"],
  settings: {
    react: {
      version: "detect",
    },
  },
  overrides: [
    {
      files: ["*.config.{ts,js}", "**/*.stories.{tsx,ts,js,jsx}"],
      rules: {
        "import/no-default-export": "off",
      },
    },
  ],
  parserOptions: {
    ecmaVersion: "latest",
    sourceType: "module",
  },
  plugins: ["react"],
  rules: {
    "react/no-unknown-property": [
      "error",
      {
        ignore: [
          "p",
          "m",
          "w",
          "h",
          "z",
          "border",
          "grid",
          "flex",
          "bg",
          "text",
          "font",
          "opacity",
          "animate",
          "transition",
          "transform",
          "align",
          "justify",
          "items",
          "block",
          "content",
          "pos",
          "box",
          "overflow",
          "underline",
          "list",
          "gradient",
          "divide",
          "gap",
          "ring",
          "icon",
          "container",
          "space",
          "table",
          "order",
          "place",
          "display",
          "shadow",
          "blend",
          "filter",
          "backdrop",
          "cursor",
          "outline",
          "select",
        ],
      },
    ],
  },
};
